on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Pull latest changes
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Deploy application using Docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.WORK_DIR }}

          echo "stop and remove existing container"
          sudo docker stop app-feedback-node  || true
          sudo docker rm app-feedback-node || true

          echo "Building new Docker Image"
          sudo docker build -t aplikasi-feedback:node .

          echo "Running new Docker Container"
          sudo docker run -d --name app-feedback-node -p 7474:3000 aplikasi-feedback:node

          echo "Deployment Completed!"
          EOF
