on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Pull latest changes
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Deploy application using Docker
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.WORK_DIR }}

          echo "stop and remove existing container"
          docker stop node-app || true
          docker rm node-app || true

          echo "Building new Docker Image"
          docker build -t webtesting_node-app .

          echo "Running new Docker Container"
          docker run -d --name node-app -p 3000:3000 webtesting_node-app

          echo "Deployment Completed!"
        EOF
